### PR TITLE
Styled Event page

### PR DESCRIPTION
**Pull request by KevinSadigh**
Styled event page by making bolded headers as well as adding coloured stars to the average review and user reviews instead of just having a decimal number also added a box around each review.

### CODE REVIEW

**Comment by HarisRasul12** [comment]
Excellent improvements form your first design - clearly formatted and shows the event reviews in a more clean manner.

Secondly well done testing with different users

**Review by HarisRasul12 — APPROVED** [review]
well done testing with different users, and well done imposing teh design of the reviews to clearly show how they feel. Looks much cleaner than your original design

**Review by zak2273 — APPROVED** [review]
Great work! The review boxes look really great. Also great work on testing with different events to see if the reviews show up properly.

**Review by Stephenwang3801 — COMMENTED** [review]
Reviewed these changes. This design looks good on the frontend

**Pull request merged**
