### PR TITLE
Edited events endpoints to return key-value pairs in GET requests

### PR DESCRIPTION
**Pull request by davidtran001**
# Improvements in Data Handling and Retrieval for Event Management System

## Overview
This pull request introduces key enhancements to our Flask-based event management system. The focus is on improving data retrieval from the PostgreSQL database and presenting it to the client in a more structured and readable format. These changes aim to increase usability, readability, and maintainability.

### Formatted Data Retrieval
- Implemented a consistent method for fetching and formatting data from the database.
- Data is now returned as a list of dictionaries, making API responses clearer and more structured.

### Endpoints Revamped
- `@event_manager_bp.route('/get/all', methods=['GET'])`: Retrieves all events.
- `@event_manager_bp.route('/get/rsvp/<int:event_id>', methods=['GET'])`: Fetches RSVP'd participants for specific events.
- `@event_manager_bp.route('/get/past', methods=['GET'])`: Lists past events.
- `@event_manager_bp.route('/get/upcoming', methods=['GET'])`: Lists upcoming events.
- `@event_manager_bp.route('/get/events_by_rsvp', methods=['GET'])`: Retrieves events sorted by RSVP count.
- `@event_manager_bp.route('/get/events_by_rating', methods=['GET'])`: Retrieves events sorted by average rating.
- `@event_manager_bp.route('/get/recent_events', methods=['GET'])`: Lists most recently added events.

## Improvements
- **Data Formatting Consistency**: Standardized method of data extraction and formatting enhances API response consistency.
- **Enhanced Readability**: Code is more readable and maintainable, with clear handling of database interactions.
- **Robust Error Handling**: Maintained strong error handling across all endpoints for reliability and debugging.

## Additional Notes
- The route for updating events (`/put/edit/<int:event_id>`) remains unchanged in this update and will be considered in future enhancements.

### CODE REVIEW

**Review by Stephenwang3801 — APPROVED** [review]
LGTM

**Comment by zak2273** [comment]
If we merge this, will it break the data retrieval from the frontend?

**Comment by zak2273** [comment]
Returning the JSON like this `return jsonify({"data": res})` results in a weird notation where I have to get the JSON data by doing `res.data.data`. Is it possible to avoid this and modify it so we can directly index into the data by just doing `res.data`?

**Review by HarisRasul12 — COMMENTED** [review]
This removes local host 3000 connection point to backend - so what was our alternative to now getting from the backend?

**Comment by davidtran001** [comment]
> If we merge this, will it break the data retrieval from the frontend?

Yes, it will since the data will have to be parsed differently. React components that use these endpoints will need to be revise.

**Comment by davidtran001** [comment]
> This removes local host 3000 connection point to backend - so what was our alternative to now getting from the backend?

I believe @zak2273 has addressed this on Discord already.

**Pull request closed without merging**
